[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
abi_stable = "0.11.3"
libloading = "0.7.4"
interface = {path = "../interface"}
stabby = { version = "36.1.1", features = ["libloading"] }
